app:
    name: My app
    description: Welcome to ${app.name}

my:
  greeting: Hello World
  list:
    values: Januar, Februar, Marz

db:
  connection: test-connection-string-here
  host: 129.0.0.1
  port: 2400

management.endpoints.web.exposure/include: "*"

server:
  port: 9091
